import { pgTable, text, serial, timestamp, integer, boolean, numeric } from "drizzle-orm/pg-core";

export const coinsTable = pgTable("coins", {
  id: serial("id").primaryKey(),
  symbol: text("symbol").notNull().unique(),
  name: text("name").notNull(),
  type: text("type").notNull().default("crypto"),
  decimals: integer("decimals").notNull().default(8),
  logoUrl: text("logo_url"),
  description: text("description"),
  status: text("status").notNull().default("active"),
  isListed: boolean("is_listed").notNull().default(true),
  listingAt: timestamp("listing_at", { withTimezone: true }),
  marketCapRank: integer("market_cap_rank"),
  currentPrice: numeric("current_price", { precision: 24, scale: 8 }).notNull().default("0"),
  change24h: numeric("change_24h", { precision: 10, scale: 4 }).notNull().default("0"),
  binanceSymbol: text("binance_symbol"),
  priceSource: text("price_source").notNull().default("binance"),
  manualPrice: numeric("manual_price", { precision: 24, scale: 8 }),
  infoUrl: text("info_url"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export type Coin = typeof coinsTable.$inferSelect;

export const networksTable = pgTable("networks", {
  id: serial("id").primaryKey(),
  coinId: integer("coin_id").notNull(),
  name: text("name").notNull(),
  chain: text("chain").notNull(),
  contractAddress: text("contract_address"),
  minDeposit: numeric("min_deposit", { precision: 24, scale: 8 }).notNull().default("0"),
  minWithdraw: numeric("min_withdraw", { precision: 24, scale: 8 }).notNull().default("0"),
  withdrawFee: numeric("withdraw_fee", { precision: 24, scale: 8 }).notNull().default("0"),
  withdrawFeePercent: numeric("withdraw_fee_percent", { precision: 8, scale: 4 }).notNull().default("0"),
  withdrawFeeMin: numeric("withdraw_fee_min", { precision: 24, scale: 8 }).notNull().default("0"),
  confirmations: integer("confirmations").notNull().default(12),
  depositEnabled: boolean("deposit_enabled").notNull().default(true),
  withdrawEnabled: boolean("withdraw_enabled").notNull().default(true),
  nodeAddress: text("node_address"),
  nodeStatus: text("node_status").notNull().default("unknown"),
  lastNodeCheckAt: timestamp("last_node_check_at", { withTimezone: true }),
  memoRequired: boolean("memo_required").notNull().default(false),
  status: text("status").notNull().default("active"),
  providerType: text("provider_type").notNull().default("custom"),
  rpcApiKey: text("rpc_api_key"),
  hotWalletAddress: text("hot_wallet_address"),
  hotWalletPrivateKeyEnc: text("hot_wallet_private_key_enc"),
  autoSweepEnabled: boolean("auto_sweep_enabled").notNull().default(false),
  autoWithdrawEnabled: boolean("auto_withdraw_enabled").notNull().default(false),
  tokenDecimals: integer("token_decimals"),
  explorerUrl: text("explorer_url"),
  lastBlockHeight: integer("last_block_height"),
  lastBlockScanned: integer("last_block_scanned"),
  blockHeightCheckedAt: timestamp("block_height_checked_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export type Network = typeof networksTable.$inferSelect;

export const pairsTable = pgTable("pairs", {
  id: serial("id").primaryKey(),
  symbol: text("symbol").notNull().unique(),
  baseCoinId: integer("base_coin_id").notNull(),
  quoteCoinId: integer("quote_coin_id").notNull(),
  minQty: numeric("min_qty", { precision: 24, scale: 8 }).notNull().default("0"),
  maxQty: numeric("max_qty", { precision: 24, scale: 8 }).notNull().default("0"),
  minNotional: numeric("min_notional", { precision: 24, scale: 8 }).notNull().default("0"),
  pricePrecision: integer("price_precision").notNull().default(2),
  qtyPrecision: integer("qty_precision").notNull().default(4),
  takerFee: numeric("taker_fee", { precision: 6, scale: 4 }).notNull().default("0.001"),
  makerFee: numeric("maker_fee", { precision: 6, scale: 4 }).notNull().default("0.001"),
  tradingEnabled: boolean("trading_enabled").notNull().default(true),
  futuresEnabled: boolean("futures_enabled").notNull().default(false),
  tradingStartAt: timestamp("trading_start_at", { withTimezone: true }),
  futuresStartAt: timestamp("futures_start_at", { withTimezone: true }),
  lastPrice: numeric("last_price", { precision: 28, scale: 8 }).notNull().default("0"),
  volume24h: numeric("volume_24h", { precision: 28, scale: 8 }).notNull().default("0"),
  quoteVolume24h: numeric("quote_volume_24h", { precision: 28, scale: 8 }).notNull().default("0"),
  high24h: numeric("high_24h", { precision: 28, scale: 8 }).notNull().default("0"),
  low24h: numeric("low_24h", { precision: 28, scale: 8 }).notNull().default("0"),
  change24h: numeric("change_24h", { precision: 10, scale: 4 }).notNull().default("0"),
  trades24h: integer("trades_24h").notNull().default(0),
  statsOverride: boolean("stats_override").notNull().default(false),
  description: text("description"),
  status: text("status").notNull().default("active"),
  maxLeverage: integer("max_leverage").notNull().default(100),
  marketSlippagePct: numeric("market_slippage_pct", { precision: 8, scale: 4 }).notNull().default("0.10"),
  mmRate: numeric("mm_rate", { precision: 8, scale: 6 }).notNull().default("0.005"),
  fundingIntervalHours: integer("funding_interval_hours").notNull().default(8),
  baseFundingRate: numeric("base_funding_rate", { precision: 10, scale: 6 }).notNull().default("0.0001"),
  fundingAutoCreate: text("funding_auto_create").notNull().default("true"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export type Pair = typeof pairsTable.$inferSelect;
